"""`make setup`: generate the deployment's own secrets and print a paste-ready ``.env`` block.

Metis owns a few secrets you must supply before a real deployment: the encrypted secret-store key,
the operator/user tokens, and the Postgres/MinIO passwords. This generates strong values for them
and prints them — it never writes a file or stores anything, because the **secret-store key must
live outside the data it protects** (env var / secret manager / KMS), not in the app. External
provider keys (Anthropic, Google, …) are *not* generated here: those are issued by the provider and
collected in the UI (Settings → Providers) or as env vars.

    make setup                 # the full block (paste into deploy/env/.env, never commit)
    make setup -- --cred-key-only   # just METIS_CRED_STORE_KEY, to enable the runtime config UI

The secret-store key (``METIS_CRED_STORE_KEY``) is special: keep it **stable** and **identical**
across the gateway and the workers — rotating or losing it makes every secret it encrypted (OAuth
tokens, stored provider keys) unrecoverable. Store it in your secret manager.
"""

from __future__ import annotations

import argparse
import secrets
from collections.abc import Sequence
from datetime import UTC, datetime

from metis_core.security import generate_key

#: Each generated secret: env var -> (generator, one-line purpose). Order is the print order.
_SECRETS: list[tuple[str, str]] = [
    ("POSTGRES_PASSWORD", "Postgres password (infra)"),
    ("MINIO_ROOT_PASSWORD", "MinIO object-store password (infra)"),
    ("METIS_GATEWAY_OPERATOR_TOKEN", "operator/admin bearer token"),
    ("METIS_GATEWAY_USER_TOKEN", "default user bearer token"),
    ("METIS_CRED_STORE_KEY", "encrypts every other secret at rest — keep stable + shared"),
]

#: The env var whose value gates durable secrets + the runtime provider config UI.
CRED_KEY = "METIS_CRED_STORE_KEY"


def _value(key: str) -> str:
    """A fresh value for ``key``: a Fernet key for the secret store, else a URL-safe token."""
    return generate_key() if key == CRED_KEY else secrets.token_urlsafe(32)


def generate_secrets(*, cred_key_only: bool = False) -> dict[str, str]:
    """Generate fresh values for the deployment-owned secrets (just the cred key if requested)."""
    keys = [CRED_KEY] if cred_key_only else [key for key, _ in _SECRETS]
    return {key: _value(key) for key in keys}


def render(values: dict[str, str], *, generated_on: str | None = None) -> str:
    """Format ``values`` as a commented ``.env`` block, paste-ready and self-documenting."""
    stamp = generated_on or datetime.now(UTC).date().isoformat()
    purpose = dict(_SECRETS)
    lines = [
        f"# Generated by `make setup` on {stamp}. Paste into deploy/env/.env (never commit), or",
        "# load these into your secret manager. Re-running generates *new* values.",
        "#",
        f"# {CRED_KEY} encrypts every other secret at rest: keep it STABLE and IDENTICAL across",
        "# the gateway and the workers — rotating or losing it makes stored secrets unrecoverable.",
        "",
    ]
    for key, value in values.items():
        lines.append(f"{key}={value}  # {purpose[key]}")
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="metis-setup",
        description="Generate the deployment's secrets and print a paste-ready .env block.",
    )
    parser.add_argument(
        "--cred-key-only",
        action="store_true",
        help=f"print only {CRED_KEY} (enough to enable the runtime provider config UI)",
    )
    args = parser.parse_args(argv)
    print(render(generate_secrets(cred_key_only=args.cred_key_only)), end="")
    return 0


if __name__ == "__main__":  # python -m metis_deploy.setup
    raise SystemExit(main())
