"""initial schema: all tables, pgvector extension, FTS + reserved embedding columns

Revision ID: 0001
Revises:
Create Date: 2026-06-18

The initial migration creates the pgvector extension, then builds every table from
the ORM metadata (the models are the source of truth in Phase 0; later migrations
are hand-written/autogenerated). FTS GIN indexes and the reserved embedding columns
are defined on the models, so create_all emits them here.
"""

from __future__ import annotations

from alembic import op

import metis_core.models  # noqa: F401  (registers tables on Base.metadata)
from metis_core.db.base import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
    op.execute("DROP EXTENSION IF EXISTS vector")
